name:                poker-rush
version:             0.1.0.0
github:              "githubuser/poker-rush"
license:             BSD3
author:              "rodlin"
maintainer:          "rod.yeti@outlook.com"
copyright:           "2018 rodlin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/rod-lin/poker-rush>

dependencies:
- base >= 4.7 && < 5
- monad-loops
- random-shuffle
- readline

library:
  source-dirs: src

executables:
  poker-rush-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - poker-rush

# tests:
#   poker-rush-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - poker-rush
